CREATE TABLE dbo.Users (
    UserID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARBINARY(64) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastUpdatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Store password hashes generated by the application layer. Do not commit real
-- credentials or plaintext passwords to source control.
INSERT INTO dbo.Users (Username, PasswordHash)
VALUES (N'example_user', 0x0123456789ABCDEF);

UPDATE dbo.Users
SET PasswordHash = 0xABCDEF0123456789,
    LastUpdatedDate = SYSUTCDATETIME()
WHERE Username = N'example_user';

SELECT
    UserID,
    Username,
    CreatedDate,
    LastUpdatedDate
FROM dbo.Users;
