name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or '16' based on your compatibility

      - name: Install dependencies
        working-directory: ./client
        run: |
          npm install react@18.2.0 react-dom@18.2.0
          npm install

      - name: Build app
        working-directory: ./client
        run: |
          sudo chmod +x client/node_modules/.bin/react-scripts  
          sudo chmod +x ./node_modules/.bin/react-scripts
          npm run build

      - name: Fix permissions (optional, usually only needed on self-hosted runners)
        if: runner.os == 'Linux'
        run: sudo chmod +x client/node_modules/.bin/react-scripts

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_OCEAN_0F03A230F }}
          repo_token: ${{ secrets.PAT }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "./client"
          api_location: "./api"
          output_location: "client/build"
          ###### End of Repository/Build Configurations ######


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_OCEAN_0F03A230F }}
          action: "close"
