name: Build and deploy React app to Azure Web App - react-app-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Upload build artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: react-app-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download build artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app-build
          path: build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A2F50BB87DA445886E729E7390CD7E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B395185619EC4ABFB5CC33596439B760 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A8F874F452D44423AEE657B89181B29E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nwmiws'
          slot-name: 'Production'
          package: ./build
